package com.myspace.business_central;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testHooks implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;

	public testHooks() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public testHooks(java.lang.String id) {
		this.id = id;
	}

}